name: bas_clean_architecture
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #iOS
  cupertino_icons: ^1.0.2

  #Notifier
  fluttertoast: ^8.1.2

  #Theme
  dynamic_color: ^1.5.4

  #Local cache
  shared_preferences: ^2.0.17

  #Network
  dio: ^5.1.2
  graphql_flutter: ^5.1.2

  #UI
  responsive_table: ^0.2.0+2
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3

  #Page transition
  page_transition: ^2.0.9

  #Routing
  go_router: ^7.0.1

  #easy loading
  flutter_easyloading: ^3.0.5

  #Expandable
  expandable: ^5.0.1

  #Firebase
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  firebase_auth: ^4.6.0

  #Multiple languages
  easy_localization: ^3.0.1

  #Notificaiton
  flutter_local_notifications: ^14.0.0+2

  #Dependency Injection
  get_it: ^7.2.0

  #Env
  flutter_dotenv: ^5.0.2

  #State management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  #Icons
  material_design_icons_flutter: ^6.0.7096

  #Bottombar
  persistent_bottom_nav_bar: ^5.0.2

  #url_strategy
  url_strategy: ^0.2.0

  #pin_code_field
  pin_code_fields: ^7.4.0
  url_launcher: ^6.1.10
  rxdart: ^0.27.7
  path_provider: ^2.0.14
  flutter_isolate: ^2.0.4
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1
  image_picker: ^0.8.7+4
  carousel_slider: ^4.2.1
  flutter_calendar_carousel: ^2.4.1

  #Snack
  another_flushbar: ^1.10.29

  #Phone
  country_code_picker: ^3.0.0
  adaptive_dialog: ^1.8.3
  star_menu: ^3.1.4

  flutter_cupertino_datetime_picker: ^3.0.0
  jwt_decoder: ^2.0.1
  flutter_date_pickers: ^0.1.0
  flutter_screenutil: ^5.7.0
  dotted_border: 2.0.0+3
  flutter_dropzone: 3.0.6
  file_picker: ^5.0.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/countries/
    - assets/images/
    - assets/localization/
    - assets/fonts/

  fonts:
    - family: DMSerifDisplay-Regular
      fonts:
        - asset: assets/fonts/dmserifdisplay/DMSerifDisplay-Regular.ttf

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/plusjakartasans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/plusjakartasans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/plusjakartasans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/plusjakartasans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/plusjakartasans/PlusJakartaSans-SemiBold.ttf
          weight: 600
