name: Test, Build and Release

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.3"

      - name: Clean Cache
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      #Setup automation build Web and Distribute with Firebase Flutter
      #- run: flutter build web --web-renderer canvaskit --release

      # - name: Deploy to hosting
      #   run: |
      #     echo "Deploying to Firebase..."
      #     FIREBASE_CLI_URL=$(curl -s -L -o /dev/null -w %{url_effective} https://firebase.tools/bin/linux/latest)
      #     wget -O firebase-cli.tar.gz --no-check-certificate "$FIREBASE_CLI_URL"
      #     curl -sL https://firebase.tools | bash
      #     firebase deploy --token $FIREBASE_TOKEN

      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      #Setup automation build Mobile App and Distribute with Firebase Flutter
      - run: flutter build apk

      - name: Push To Release
        uses: ncipollo/release-action@v1
        with:
          atifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}

      - name: Upload atifact to Firebase distribute
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: build/app/outputs/apk/release/app-release.apk

        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
